#pragma config(Sensor, S1,     ColorSensor,    sensorColorNxtFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void DecideOnRedOrOrange();

int redOrOrange;
bool isRed = false;
bool isOrange = false;
bool isBlue = false;
bool isGreen = false;
bool isYellow = false;
bool isWhite = false;
bool isBlack = false;

short rawValues[4];
short red;
short green;
short blue;
short ambient;

task main()
{
	while(1){
		switch(SensorValue[S1]){
			case BLUECOLOR:		isBlue = true;
			break;

			case GREENCOLOR:	isGreen = true;
			break;

			case YELLOWCOLOR:	isYellow = true;
			break;

			case REDCOLOR:		isRed = true;
			//DecideOnRedOrOrange();
			break;

			case WHITECOLOR:	isWhite = true;
			break;

			case BLACKCOLOR:

			default:						;
			break;
		}

		sleep(1000);
		isRed = false;
		isOrange = false;
		isBlue = false;
		isGreen = false;
		isYellow = false;
		isWhite = false;
		isBlack = false;
	}
}

void DecideOnRedOrOrange(){
	getColorSensorData(S1, colorRaw, &rawValues[0]);
	red = rawValues[0];
	green = rawValues[1];
	blue = rawValues[2];
	ambient = rawValues[3];

	if(blue)
	{
	redOrOrange = 500*(green)/(blue);

	if(redOrOrange < 235)
		isRed = true;
	else
		isOrange = true;
	}
}
